### ISSUE TITLE
Create a list of goals for the finished site

### ISSUE THREAD

**Issue by llamas01** [levimichael/we-are-CEDM#1]
By creating a list of goals and ideals that the finished site will be based on, we can easily form a clear course of action for next steps throughout the project.

**Comment by levimichael** [comment]
maybe for the initial launch it would be good to just make a google survey and distribute that. I'll do that. then we can get the ordered list of goals based on aggregate rankings from the community.

**Comment by llamas01** [comment]
That sounds like an excellent idea!

**Comment by levimichael** [comment]
Form is live here: https://goo.gl/forms/862nEWicmqVUTvdE3
